baseurl = "https://justinhayes.me/"
languageCode = "en"
title = "Justin Hayes"
theme = "tale"
copyright = "&copy; <a href=\"https://justin-hayes.github.io/\">Justin Hayes</a> 2016"
#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Justin Hayes"
subtitle = "Justin Hayes's Blog"
description = "Nothing-special thoughts"

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/justin-hayes"
fa_icon = "fa-github"

#[[params.social]]
#url = ""
#fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
